name: flutter_app_expiry
description: >
  Enforce trial periods in Flutter apps. Set a deadline,
  auto-lock on expiry, and protect your work. Zero dependencies.

version: 1.2.5
homepage: https://github.com/imjazzdev/flutter_app_expiry
repository: https://github.com/imjazzdev/flutter_app_expiry
issue_tracker: https://github.com/imjazzdev/flutter_app_expiry/issues
topics:
  - flutter
  - expiry
  - trial
  - license
  - watermark


screenshots:
  - description: "Logo of Flutter App Expiry"
    path: assets/icon-library.png



# ===========================================================
environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
